# Dolphin GFX — generic Android baseline
# Target: dolphin-emu/Config/GFX.ini

[Settings]
VideoBackend = Vulkan
AspectRatio = 0
EFBScale = 2
MaxAnisotropy = 0
MSAA = 0
SSAA = False
TextureFiltering = 0
DisableFog = False
BackendMultithreading = True
HiresTextures = False
CacheHiresTextures = True
ConvertHiresTextures = False
InternalResolutionFrameDumps = False

[Hacks]
EFBAccessEnable = True
EFBAccessCacheEnable = False
EFBToTextureEnable = True
EFBScaledCopy = True
EFBEmulateFormatChanges = False
SkipDuplicateXFBs = True
XFBToTextureEnable = True
ImmediateXFBEnable = False
